[MISC] Compute layout also takes positions.
seqan/hibf pull request #210
Opened 2024-07-09 12:45 UTC by smehringer

Next step to make the hibf lib compatible with the incoming partitioned HIBF and Fast Layouted HIBF.

In that case, we do not always layout ALL user bins `[0,n-1]` but only part of them (e.g. only the first 10 for the first partition). Therefore, a layout needs to be able to be computed given an extra position vector, s.t. auxiliary information, e.g. sketches, remain untouched but I can pick whatever I need.

Fot the original layout, we just need to pass the original positions `[0,n-1]`.

2024-07-09 12:52 UTC, smehringer commented on src/layout/compute_layout.cpp
>      concurrent_timer union_estimation_timer;
Note: There are two overloads:

overload 1)
```
layout compute_layout(config const & config,
                      std::vector<size_t> const & kmer_counts,
                      std::vector<sketch::hyperloglog> const & sketches,
                      std::vector<size_t> && positions,
                      concurrent_timer & union_estimation_timer,
                      concurrent_timer & rearrangement_timer)
```

overload 2)
```
layout compute_layout(config const & config,
                      std::vector<size_t> const & kmer_counts,
                      std::vector<sketch::hyperloglog> const & sketches)
```

I only adjusted overload 1, since this is the one I use in the `hibf::hierarchical_interleaved_bloom_filter` and in chopper. Overload 2 is only used in `determine_best_tmax`.

In general we have to think about whether we still want `determine_best_tmax` as I am not sure if it correctly calculates the sizes. Didn't we have an issue regarding this?

2024-07-09 13:38 UTC, eseiler requested changes

2024-07-09 13:38 UTC, eseiler commented on include/hibf/layout/compute_layout.hpp
> +                      std::vector<size_t> && positions,
```suggestion
                      std::vector<size_t> positions,
```

2024-07-09 13:38 UTC, eseiler commented on src/layout/compute_layout.cpp
> +                      std::vector<size_t> && positions,
```suggestion
                      std::vector<size_t> positions,
```

2024-07-09 13:38 UTC, eseiler commented on src/hierarchical_interleaved_bloom_filter.cpp
> +    std::vector<size_t> positions = [&kmer_counts]()
Since we are using this in multiple positions, would it make sense to put it into some header?

```cpp
template <typename value_t = size_t>
HIBF_CONSTEXPR_VECTOR std::vector<value_t> iota_vector(size_t const size)
{
    std::vector<value_t> result(size);
    std::iota(result.begin(), result.end(), value_t{});
    return result;
}
```

and then use `auto positions = iota_vector(kmer_counts.size());`,
or because we are always moving it anyway:

```cpp
    auto layout = layout::compute_layout(configuration,
                                         kmer_counts,
                                         sketches,
                                         iota_vector(kmer_counts.size()), // instead of std::move(positions)
                                         layout_union_estimation_timer,
                                         layout_rearrangement_timer);
```


Is `compute_layout` at any point called with some `positions` different from just the `iota`? Then we wouldn't need the parameter at all.
If it is not, it could also be the last parameter:


```cpp
layout compute_layout(config const & config,
                      std::vector<size_t> const & kmer_counts,
                      std::vector<sketch::hyperloglog> const & sketches,
                      concurrent_timer & union_estimation_timer,
                      concurrent_timer & rearrangement_timer,
                      std::vector<size_t> && positions = iota_vector(kmer_counts.size());
```

2024-07-09 13:38 UTC, eseiler commented on src/hierarchical_interleaved_bloom_filter.cpp
> +        std::iota(ps.begin(), ps.end(), 0);
If we don't do a function, we should definitely change this in all occurrences:

```suggestion
        std::iota(ps.begin(), ps.end(), size_t{});
```

2024-07-09 13:38 UTC, eseiler commented on src/layout/compute_layout.cpp
> +    assert(*std::ranges::max_element(positions) <= config.number_of_user_bins);
```suggestion
    assert(std::ranges::max(positions) <= config.number_of_user_bins);
```

2024-07-09 13:41 UTC, eseiler commented on src/layout/compute_layout.cpp
>      concurrent_timer union_estimation_timer;
Yes we did. `determine_best_tmax` is also only in chopper, no? Shouldn't it then be enough if chopper just provides this overload for it to use?

In general, I don't like the signature of `compute_layout`, maybe we want to think about changing it. I especially don't like that the timers are separate parameters. Maybe they could be mutable members of the config or something

2024-07-11 06:23 UTC, smehringer commented on src/layout/compute_layout.cpp
>      concurrent_timer union_estimation_timer;
I agree, that passing the timers here is not nice. Mutable config elements would be fine for me. (separate PR)

2024-07-11 06:25 UTC, smehringer commented on include/hibf/layout/compute_layout.hpp
> +                      std::vector<size_t> && positions,
Yes, I wanted to enforce moving in order to prevent accidental copying.
I think it makes clear that it is a parameter only needed for within the function, although it still has to be given from the outside. And (answering a question below already) in the partitioned HIBF this function will be called with different positions but the same sketches per partition.

2024-07-11 06:27 UTC, smehringer commented on src/hierarchical_interleaved_bloom_filter.cpp
> +    std::vector<size_t> positions = [&kmer_counts]()
I like the iota vector!

In this PR, `compute_layout` is not called with any different `positions`. But the partitioned HIBF will call this with different positions for each partition.

2024-07-11 06:39 UTC, smehringer commented on include/hibf/misc/iota_vector.hpp
> +}
```suggestion
}

```

2024-07-11 09:20 UTC, eseiler approved these changes

2024-07-11 09:39 UTC, merged