[FEATURE] Add data_store::validate
seqan/hibf pull request #230
Opened 2024-09-10 23:13 UTC by eseiler

Part 1 of #227

2024-09-10 23:14 UTC, seqan-actions commented
Documentation preview available at https://docs.seqan.de/preview/seqan/hibf/230

2024-09-11 07:20 UTC, smehringer requested changes
tiny add ons

2024-09-11 07:20 UTC, smehringer commented on src/layout/data_store.cpp
> +
```suggestion

   if (positions.size() > kmer_counts->size())
        throw std::invalid_argument{"[HIBF ERROR] data_store::positions must be smaller or euqal in size to kmer_counts."};

```

2024-09-11 07:20 UTC, smehringer commented on src/layout/hierarchical_binning.cpp
> +                throw std::invalid_argument{"[HIBF ERROR] data_store::sketches must not be nullptr."};
```suggestion
                throw std::invalid_argument{"[HIBF ERROR] data_store::sketches must not be nullptr is union estimation or rearrangement is enabled."};
```

2024-09-12 13:20 UTC, smehringer approved these changes

2024-09-12 14:33 UTC, merged