[FEATURE] Empty bins in layout
seqan/hibf pull request #251
Opened 2024-12-03 18:05 UTC by eseiler

2024-12-03 18:09 UTC, seqan-actions commented
Documentation preview available at https://docs.seqan.de/preview/seqan/hibf/251

2024-12-03 18:47 UTC, eseiler commented on include/hibf/layout/hierarchical_binning.hpp
>          assert(data != nullptr);
This line could be removed, no?
data_ is a reference, so this pointer can never be null

2024-12-12 19:05 UTC, smehringer requested changes

2024-12-12 19:05 UTC, smehringer commented on src/layout/hierarchical_binning.cpp
> +    return tmax_without_empty_bins(needed, config.empty_bin_fraction);
```suggestion
    return tmax_without_empty_bins(needed, config.empty_bin_fraction); // subtract empty bins before layouting
```

2024-12-12 19:05 UTC, smehringer commented on src/layout/hierarchical_binning.cpp
> +        size_t const number_of_technical_bins = tmax_without_empty_bins(num_user_bins, config.empty_bin_fraction);
```suggestion
        size_t const number_of_technical_bins = tmax_without_empty_bins(num_user_bins, config.empty_bin_fraction); // subtracts empty bins
```

2024-12-12 19:05 UTC, smehringer commented on test/unit/hibf/layout/hierarchical_binning_test.cpp
> +TEST(hierarchical_binning_test, small_example_two)
instead of introducing `small_example_two` you could directly add an empty bin test that has tmax = 5, an empty bin fraction that results in layouting with 4 technical bins, and then the result should be equivalent to the result of `small_example`

2024-12-12 19:07 UTC, smehringer commented on include/hibf/misc/tmax_without_empty_bins.hpp
> +[[nodiscard]] constexpr size_t tmax_without_empty_bins(size_t const tmax, double const fraction) noexcept
```suggestion
[[nodiscard]] constexpr size_t subtract_empty_bins(size_t const tmax, double const fraction) noexcept
```

2024-12-12 19:10 UTC, smehringer commented on include/hibf/config.hpp
> +    double empty_bin_fraction{};
please write a more detailed description

2025-01-29 17:57 UTC, SGSSGene approved these changes

2025-01-29 17:57 UTC, SGSSGene commented on include/hibf/layout/hierarchical_binning.hpp
> +        num_technical_bins{data->previous.empty() ? subtract_empty_bins(config.tmax, config.empty_bin_fraction)
Maybe this variable should be renamed? something like "num_technical_bins_in_use" or "occupied_technical_bins". So it gets clear that it does not include the empty bin?

2025-01-29 18:58 UTC, eseiler commented on include/hibf/layout/hierarchical_binning.hpp
> +        num_technical_bins{data->previous.empty() ? subtract_empty_bins(config.tmax, config.empty_bin_fraction)
The layout isn't aware how many technical bins there actually are.
In the context of the layout, there are only ever `num_technical_bins`.
The algorithm doesn't really care whether you want 128 or 125 technical bins.

The meaning of occupied/unoccupied is introduced outside the layout.
The HIBF knows that it wants empty bins and has a tmax of 128.
So it then requests a layout for 125 bins. And the last 3 are empty.

Does that make sense?

2025-01-29 19:45 UTC, SGSSGene approved these changes

2025-01-29 19:45 UTC, SGSSGene commented on include/hibf/layout/hierarchical_binning.hpp
> +        num_technical_bins{data->previous.empty() ? subtract_empty_bins(config.tmax, config.empty_bin_fraction)
So in your example, it is specifically leaving 3 bins out of the layout computation so it can be filled later, as it likes.

2025-01-30 12:36 UTC, merged