[FEATURE] Track occupancy in IBF
seqan/hibf pull request #257
Opened 2024-12-10 13:20 UTC by eseiler

Blocked by 
* #251 
* #253 
* #254 
* #256

2024-12-10 13:31 UTC, seqan-actions commented
Documentation preview available at https://docs.seqan.de/preview/seqan/hibf/257

2025-01-29 18:18 UTC, SGSSGene requested changes
The assert in combination with the `if` statement is confusing...

2025-01-29 19:00 UTC, eseiler commented on src/build/insert_into_ibf.cpp
> +    }
The block should be always executed, but
```cpp
        assert(std::ranges::all_of(it,
                                   it + diff,
                                   [](size_t value)
                                   {
                                       return value == 0u;
                                   }));
```
should only happen in debug.



```cpp
    if (ibf.track_occupancy && chunk_view.size() < number_of_bins)
    {
        size_t const diff = number_of_bins - chunk_view.size();
        auto it = ibf.occupancy.begin() + bin_index + chunk_view.size();
        std::ranges::fill_n(it, diff, 1u);
    }
```
should always happen.

2025-01-29 20:02 UTC, SGSSGene approved these changes

2025-01-29 20:02 UTC, SGSSGene commented on src/build/insert_into_ibf.cpp
> +    }
I missed read the `assert(chunk_view.size() <= number_of_bins);` line. Yes this looks good.

2025-01-30 12:45 UTC, merged